ALTER TABLE "Token" ADD COLUMN "fuente_id" INTEGER REFERENCES "FuenteDatos"("id") ON DELETE SET NULL;
ALTER TABLE "Token" ADD COLUMN "usuario_api" VARCHAR(100);
ALTER TABLE "Token" ADD COLUMN "activa" BOOLEAN NOT NULL DEFAULT true;
