CREATE TABLE "PasswordResetToken" (
  "id" SERIAL PRIMARY KEY,
  "usuario_id" INTEGER NOT NULL REFERENCES "Usuario"("id"),
  "token" TEXT NOT NULL UNIQUE,
  "expires_at" TIMESTAMP NOT NULL,
  "used" BOOLEAN NOT NULL DEFAULT false,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
